baseURL = "https://igjit.github.io/"
languageCode = "ja"
hasCJKLanguage = true
title = "igjit status"
theme = "hugo_theme_pickles"

[params]
  twitter = "igjit"
  github = "igjit"
  ga_api_key = "UA-57209397-3"
  author = "igjit"
  avatar = "/images/avatar.png"
  bio = "Software Engineer"
  subtitle = "echo $?"
  custom_css = ["css/custom.css"]

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "Slides"
    url = "https://igjit.github.io/slides/"
    weight = 2
